"""Added admin hospital route

Revision ID: 656f90ac6525
Revises: 6ae82e30ce8a
Create Date: 2024-12-27 13:17:02.019483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656f90ac6525'
down_revision = '6ae82e30ce8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_hospital', 'hospital', ['hospital_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hospital_id')

    # ### end Alembic commands ###
