"""Added doctor,appoitment, medical history

Revision ID: 7093db880d1c
Revises: 241674c65f3e
Create Date: 2024-12-27 16:56:46.733626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7093db880d1c'
down_revision = '241674c65f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.drop_table('doctor')
    op.drop_table('client')
    op.drop_table('medical_history')
    op.drop_table('doctor_availability')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_availability',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), nullable=False),
    sa.Column('day_of_week', sa.VARCHAR(length=10), nullable=False),
    sa.Column('start_time', sa.VARCHAR(length=5), nullable=False),
    sa.Column('end_time', sa.VARCHAR(length=5), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('hospital_id', sa.INTEGER(), nullable=False),
    sa.Column('entry_date', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=False),
    sa.Column('address', sa.VARCHAR(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('doctor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('specialty', sa.VARCHAR(length=150), nullable=True),
    sa.Column('hospital_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), nullable=False),
    sa.Column('hospital_id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
