"""Added doctor,appoitment, medical history

Revision ID: 9035e81cb23a
Revises: bacb4f335e23
Create Date: 2024-12-27 16:34:24.335597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9035e81cb23a'
down_revision = 'bacb4f335e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_history')
    op.drop_table('doctor')
    op.drop_table('appointment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('time', sa.TIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('specialization', sa.VARCHAR(length=100), nullable=False),
    sa.Column('availability', sa.VARCHAR(length=500), nullable=False),
    sa.Column('hospital_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('hospital_id', sa.INTEGER(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
