"""Add security_key to Doctor

Revision ID: a863dd45c4a5
Revises: 860f7773f5cd
Create Date: 2025-03-13 11:22:40.408810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a863dd45c4a5'
down_revision = '860f7773f5cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_key', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('security_key')

    # ### end Alembic commands ###
